#1.7.0
#install! 'cocoapods', :generate_multiple_pod_projects => true

target 'IJKMediaDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IJKMediaDemo

  platform :ios, '13.0'

  pod 'IJKMediaPlayerKit', :path => '../../'
#  pod 'ffmpeg-kit', :path => '/Users/moqiaowen/Downloads/ffmpeg-kit'
end

post_install do |installer|

  # show framework headers
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      dir = project.path + "../#{target.name}"
      if Dir.exist?(dir)
        Dir.glob("#{dir}/**/*.framework") do |p|
          group = project.pod_group(target.name)
          headersDir = "#{p}/Headers"
          if Dir.exist?(headersDir)
            project.add_file_reference(headersDir, group, true)
          end
        end
      end
    end
  end

end
